# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IschiaSeismicScenario
                                 A QGIS plugin
 Create a seismic shaking scenario for Ischia Island
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-30
        copyright            : (C) 2021 by Salvatore D'Amico - INGV-OE
        email                : salvatore.damico@ingv.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IschiaSeismicScenario class from file IschiaSeismicScenario.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ischia_seismic_scenario import IschiaSeismicScenario
    return IschiaSeismicScenario(iface)
